# go快速入门笔记-函数

## 1函数声明

每个函数声明都包含一个名字、一个行参列表、一个可选的返回列表以及函数体：

```Go
func name( paramter-list ) ( return-list ){
    body
}
```

函数的类型称作```函数签名```。当两个函数拥有相同的```行参列表```和```返回列表```时，认为这两个函数的类型签名是相同的。而行参和返回值的名字不会影响函数类型。  
行参变量都是函数的```局部变量```，初始值由调用者提供的实参传递。  
```实参是按值传递的```，所以函数接收到的是每个实参的副本;修改函数的行参变量并不会影响调用者提供的实参。如果提供的实参包含引用类型，比如指针、slice、map、函数、或者通道，那么当函数使用行参变量时就有可能会间接地修改实参变量。

## 2.递归

函数可以```递归```调用。递归调用是指函数可以直接或者间接调用自己。下面给一个最简单的例子,给定一个整数数字字符串，现在需要你从右开始往前数，长度为3的在其中间插入一个英文逗号，例如：```1234567890 =》 1,234,567,890```.下面方式通过递归就很容易实现。

```Go
func comma(strNumber string) string {
	n := len(strNumber)
	if n <= 3 {
		return strNumber
	}
	return comma(strNumber[0:n-3]) + "," + strNumber[n-3:]
}
```

使用递归需要注意的是递归一定有结束条件。例如上面的结束条件就是```n<=3```。如果没有结束条件将导致超出栈的最大深度导致栈溢出。

## 3.多返回值

一个函数能够返回不止一个结果。在大多数其他语言中，例如JAVA中是无法同时返回多个值。如果想要返回多个值需要把多个返回值包装成一个新的对象单独返回，这样操作起来很麻烦。但是Go是支持多返回值的。例如下面这个：

```Go
func f5() (string, int) {
	return "happy new year",2020
}
```

但是多值将导致一个问题，在Go中不能定义没有使用的变量，意思就是你定义了变量，但是没有使用编译将无法通过。如果返回多个值，我只想使用其中之一如何操作呢？

```Go
str, _ := f5()
```

我们只需要使用```_```忽略该值即可。

## 4.错误

有很多函数并不能保证一定能够成功返回，因为有些因素并不受设计者的掌握。例如任何操作I/O的函数都一定会面对可能的错误。如果函数调用发生错误十，Go会在函数的返回值中附加一个错误返回。在其他语言中，例如JAVA,它通过try-catch捕捉异常的方式来处理异常。

### 4.1错误处理策略

当一个函数调用返回一个错误时，调用者应该负责检查错误并采取合理的处理应对。

- 最常见的就是将错误传递下去。
- 对于不固定或者不可预测的错误，在短暂的间隔后对操作进行重试。超过一定次数和限定时间后再报错退出。
- 输出错误停止程序
- 记录错误信息继续运行
- 安全的忽略整个日志

### 4.2文件结束标识

调用者反复的读取固定大小的块直到文件耗尽，调用者必须把读取到文件尾的情况与其他情况区别对待。为此，io包保证任何由文件结束引起的读取错误，始终都会得到一个与众不同的错误-io.EOF

## 5.函数变量

函数可以当作变量，可以赋给其他变量或者传递或者从其他函数中返回。函数变量可以像其他函数一样调用。

```Go
package main

import "fmt"

func main() {
	// 把函数赋给f
	f := sayHello
	fmt.Printf("f type is :%T\n",f)
	f()
}

func sayHello() {
	fmt.Println("Hello")
}
```

打印结果如下：

```Go
f type is :func()
Hello
```

从上面结果可以看出函数可以赋给某个变量，而且还是有类型的，被赋值的变量还可以正常执行函数。
需要注意的是，函数是不可以比较的，所以不能把函数作为map的key。  

函数可以作为变量，这意味这函数的行为可以作为参数传递。例如下面这个：

```Go
// op 行参是一个函数，可以传入一个动作
func Operation(op func(x, y int) int, x, y int) int {
	return op(x,y)
}

// 加法
func Add(x, y int) int {
	return x+y
}
// 减法
func Sub(x, y int) int {
	return x-y
}
```

上面一共定义了三个方法，第一个Operation接收一个操作(方法)和两个int参数，而后面的两个方法都是简单的加减法操作。下面调用他们

```Go
    // 加法
	add := Add
	result := Operation(add, 1, 2)
	fmt.Printf("result : %d\n",result)
	// 减法
	sub := Sub
	result = Operation(sub,1,2)
	fmt.Printf("result : %d\n",result)
```

我们将动作（方法）传入到Operation方法中。根据传入的动作不同，执行不同的操作。

## 6.匿名函数

命名函数只能在包级别的作用域进行声明，但那是我们能够使用```函数字面量```在任何表达式内指定函数变量。函数字面量就像函数的声明，但在func关键子后面没有函数名称。它是一个表达式，它的值叫```匿名函数```。例如上面那个例子，我们可以使用更简便的方法来写：

```Go
    //乘法
	mul := func(x,y int) int {return x*y}
	result = Operation(mul, 1, 2)
	fmt.Printf("result : %d\n",result)
```

更重要的是以这种方式定义的函数能够获取整个词发环境，里层函数可以使用外层函数中的变量。例如，使用这种特性，我们可以实现一个计数器。

```Go
// 计数器
func counter(initValue int) func() int {
	return func() int {
		initValue++
		return initValue
	}
}
```

调用代码如下：

```Go
//计数器使用，获取一个初始值为100的计数器
	c1 := counter(100)
	fmt.Println(c1())
	fmt.Println(c1())
	fmt.Println(c1())
	fmt.Println(c1())
	//计数器使用，获取一个初始值为0的计数器
	c2 := counter(0)
	fmt.Println(c2())
	fmt.Println(c2())
	fmt.Println(c2())
	fmt.Println(c2())
```

最后的打印结果如下：

```Go
101
102
103
104
1
2
3
4
```

这种函数使用方式就叫做```闭包```。

## 7.变长函数

变长函数被调用的时候可以有可变的参数个数。例如最常见的```fmt.Printf```。在参数列表最后的类型名称之前使用```...```表示声明一个变长函数，调用这个函数的时候可以传递该类型任意数目的参数。例如下面这个累计求和的函数：

```Go
//可变参数
func Sum(values ...int) int {
	total := 0
	for _, value := range values {
		total+= value
	}
	return total
}
```

调用方式如下：

```Go
total := Sum(1, 2, 3, 4, 5, 6, 7, 8, 9)
```

或者：

```Go
values := []int{1,2,3,4,5,6,7,8,9}
total := Sum(values...)
```

在```Sum```函数内部，```values```是一个int类型的slice.

## 8.延迟函数调用

- Go中的```defer```是用来延迟执行函数的。而且延迟发生在return之后。例如：

```Go
func a() string {
	defer b()
	return "hello world"
}
```

函数b()会在return之后执行。

- 如果在一个函数中，有多个defer被调用，那么它们将按照倒序执行（LIFO）。

```Go
func f8() {
	defer fmt.Println(4)
	defer fmt.Println(3)
	defer fmt.Println(2)
	defer fmt.Println(1)
}
```

最后的输出顺序将会是```1,2,3,4```。  

- 被defer的函数的```参数在defer时确定```。

```Go
// 被defer的参数在defer时确定
func f9() {
	i := 0
	defer fmt.Printf(i)
	i++
}
```

代码执行打印i的值为0.因为i的值在defer已经确定为0了。  
- 被```defer```的函数```可以读取和修改```带名称的返回值

```Go
func f10() int {
	i := 0
	defer func() {i++}()
	return i
}

func f11() (i int) {
	defer func() {i++}()
	return i
}
```

上面的两个函数，f10最后的执行结果为0,而f11()执行的结果为1.

## 9.panic和recover

Go语言在编译时会捕获很多错误，但是有些错误必须在运行是才能进行检查。例如访问数组越界或者解引用空指针等等，这类错误将会导致宕机。当宕机时，```正常的程序执行会终止，goroutine中所有的延迟函数会执行，然后退出并留下一条日志消息```。

```Go
func p1(index int) {
	arrays := [3]int{1,2,3}
	defer func() {
		fmt.Println("defer 1")
	}()
	defer func() {
		fmt.Println("defer 2")
	}()
	defer func() {
		fmt.Println("defer 3")
	}()
	fmt.Println(arrays[index])
	fmt.Println("method over")
}
```

调用函数```p1()```,正常流程会先打印数组中的值，然后打印```method over```,然后按照LIFO的顺序打印defer中的内容。如果我们给出的参数大小超过数组的最大索引，将会导致异常，程序执行中断，但是在中断前，会执行defer函数，然后打印出错误的信息。  

并不是所有宕机都是运行时发生的。我们可以通过```panic```调用宕机函数。

```Go
func p2(operation string) string{
	switch operation {
	case "+":
		return "加法"
	case "-":
		return "减法"
	case "*":
		return "乘法"
	case "/":
		return "除法"
	default:
		panic(fmt.Sprintf("未知的操作%s\n",operation))
	}
}
```

上面的代码中，我们遇见不认识的操作，所以我们无法处理，手动调用```panic```函数。这样我们就能终止程序继续运行。但是有的```panic```我们可以处理，那我们如何从panic中恢复呢？

```Go
func p3(x,y int) int {
	defer func() {
		if err := recover(); err != nil {
			fmt.Println(err)
		}
	}()
	r := x / y
	fmt.Println(r)
	return r
}
```

上述代码，调用```p3(1,0)```将导致宕机，但是我们定义了defer函数，defer函数中的recover可以帮助我们处理异常。但有一点需要注意的是，```recover```必须是defer,否这将无效。